version: "3"

services:
  web:
    build:
      context: .
      dockerfile: build/web.Dockerfile
    environment:
      - "NODE_PATH=/app/node_modules/"
      - "ENVIRONMENT=${ENVIRONMENT}"
      - "PORT=${PORT}"
      - "API_TOKEN=${API_TOKEN}"
      - "API_ADMIN_TOKEN=${API_ADMIN_TOKEN}"
      - "API_ADMIN_IP=${API_ADMIN_IP}"
      - "API_CRONTAB_TOKEN=${API_CRONTAB_TOKEN}"
      - "API_CRONTAB_IP=${API_CRONTAB_IP}"
      - "DATABASE_LOCATION=${DATABASE_LOCATION}"
      - "REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}"
      - "REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}"
      - "REDDIT_USERNAME=${REDDIT_USERNAME}"
      - "REDDIT_PASSWORD=${REDDIT_PASSWORD}"
    ports:
      - 3010:3010
    restart: always
    volumes:
      - acm-data:/data
  crontab:
    build:
      context: .
      dockerfile: build/crontab.Dockerfile
    environment:
      - "PORT=${PORT}"
      - "API_CRONTAB_TOKEN=${API_CRONTAB_TOKEN}"
    restart: always
volumes:
  acm-data:
