name: "CI"

on:
  pull_request:
    branches: [main]

# Allow one run of this workflow per branch and cancel existing runs if triggered again
concurrency:
  group: acm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-restore